version: '3'

services:

  ghost:
    container_name: ghost
    image: ghost:2-alpine
    restart: always
    ports:
      - 2368:2368
    environment:
      database__client: mysql
      # values to be populated
      database__connection__host: 
      database__connection__user: mysql
      database__connection__password: secret
      database__connection__database: ghost
      database__connection__port: 3306
    volumes:
      - /usr/ghost/content:/var/lib/ghost/content

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    depends_on:
      - ghost
    ports:
      - 80:80
    