version: '3'
services:
  ghost:
    container_name: ghost
    image: ghost:2-alpine
    restart: always
    ports:
      - 2368:2368
    environment:
      url: https://haomingyin.com
      database__client: mysql
      database__connection__host: "terraform-20190225074633734800000001.cuahzejpyzhi.ap-southeast-2.rds.amazonaws.com"
      database__connection__user: root
      database__connection__password: thesecret 
      database__connection__database: ghost
      database__connection__port: 3306
    volumes:
      - /usr/ghost/content:/var/lib/ghost/content

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    depends_on:
      - ghost
    ports:
      - 80:80
    